/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VtnIngreso.java
 *
 * Created on 24/07/2011, 01:51:15 AM
 */

package hospitalpets.vista;

import hospitalpets.control.CrearBaseDeDatos;
import hospitalpets.control.admin.ControlAdministraMedico;
import hospitalpets.modelo.Medico;
import java.util.Date;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author EDU
 */
public class VtnIngreso extends javax.swing.JFrame implements Runnable{
        static Vector<Medico> usuarios;
        static ControlAdministraMedico uccUsuario;
        public Date fechita;
	public Thread relo=new Thread(this);

    /** Creates new form VtnIngreso */
    public VtnIngreso() {
        initComponents();
        relo.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario:");

        jLabel2.setText("Clave:");

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblFecha.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jButton1)
                        .addGap(31, 31, 31)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuario)
                            .addComponent(txtClave, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblFecha)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblFecha)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(31, 31, 31))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-278)/2, 416, 278);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
@Deprecated
        String pass=txtClave.getText();
         String nick=txtUsuario.getText();
         boolean nohay=false;
             for (int i = 0; i < usuarios.size(); i++) {
                 if(usuarios.get(i).getNombre().equals(nick)&&usuarios.get(i).getClave().equals(pass)){
                     nohay=true;
                     new VtnPrincipal().setVisible(true);
                 }
             }
         if(nohay==false){
             JOptionPane.showMessageDialog(this, "Password o Usuario Incorrectos ." +"Ingrese de nuevo sus Datos.","Mensaje de Error",JOptionPane.ERROR_MESSAGE);
             txtClave.setText("");
             txtUsuario.setText("");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        jButton1ActionPerformed(evt);
    }//GEN-LAST:event_txtClaveActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new CrearBaseDeDatos();
        uccUsuario=new ControlAdministraMedico();
        usuarios=ControlAdministraMedico.cargarMedicos();
        final JFrame frame = new VtnIngreso();
        try{
                    java.lang.reflect.Method method =JFrame.class.getMethod("setDefaultLookAndFeelDecorated",new Class[] { boolean.class });
                    method.invoke(null, new Object[] { Boolean.TRUE });
                    method = JDialog.class.getMethod("setDefaultLookAndFeelDecorated",new Class[] { boolean.class });
                    method.invoke(null, new Object[] { Boolean.TRUE });
                    UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
                    SwingUtilities.updateComponentTreeUI(frame);
        }catch(Exception e){
                System.out.println(e);

        }

        if(usuarios.isEmpty()){
                    JOptionPane.showMessageDialog(null, "No existe ningun Usuario registrado\nSe iniciara secion como Administrador","Mensaje de Advertencia",JOptionPane.WARNING_MESSAGE);
                    uccUsuario.crearMedico("admin", "1000000000","admin","admin");
                    VtnPrincipal principal=new  VtnPrincipal();
                    SwingUtilities.updateComponentTreeUI(principal);
                    principal.setVisible(true);

        }else{
            frame.setVisible(true);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    public void run() {
        while(true){
            try{
                Thread.sleep(10);
                fechita=new Date();
                lblFecha.setText(fechita.toLocaleString());
            }catch(Exception rel){

            }
        }
    }

}
